import newed from "../api/user";
const viewShow = async (to,from,next) =>{
    if(to.meta.open){
      let userId = JSON.parse(window.sessionStorage.userInfo).identity_text;
      let liy = await newed.newed().then(data=>data)
      let index =  liy.data.findIndex(item=>item.view_authority_text === userId);
      if(index){
          next()
      }else{
          next("/noFindview")
      }
    }
}
let children = [
  {
     path:"hode",
     meta:{
       title:""
     },
     component:()=>import("../views/home/child/hode.vue")
  },
    {
      path:"addExam",
      name:"addExam",
      beforeEnter:viewShow,
       meta:{
         open:true,
         authority_text:"添加试题",
         title:"试题管理",
         user_id:["kqpvys-hpzkdt","axg8t2-oroeja"]
      },
      component:()=>import("../views/home/child/addExam.vue")
    },
    {
      path:"seeExam",
      beforeEnter:viewShow,
      meta:{
        open:true,
        authority_text:"查看试题",
        title:"试题管理",
        user_id:["kqpvys-hpzkdt","axg8t2-oroeja"]
     },
      component:()=>import("../views/home/child/seeExam.vue")
    },
    {
      path:"class",
      beforeEnter:viewShow,
      meta:{
        open:true,
        authority_text:"班级管理",
        title:"班级管理",
        user_id:["kqpvys-hpzkdt","axg8t2-oroeja"]
      },
      component:()=>import("../views/home/child/class.vue")
    },
    {
      path:"classRoom",
      beforeEnter:viewShow,
      meta:{
        authority_text:"教室管理",
         title:"班级管理",
         user_id:["kqpvys-hpzkdt","axg8t2-oroeja"]
     },
      component:()=>import("../views/home/child/classRoom.vue")
    },{
      path:"examDetail",
      beforeEnter:viewShow,
      meta:{
        authority_text:"试题详情",
      },
      component:()=>import("../views/home/child/examDetail.vue")
    },
    {
      path:"paperDetail",
      meta:{
        authority_text:"试题详情",
      },
      component:()=>import("../views/home/child/paperDetail.vue")
    },
    {
      path:"students",
      beforeEnter:viewShow,
      meta:{
        open:true,
        authority_text:"学生管理",
        title:"班级管理",
        user_id:["kqpvys-hpzkdt","axg8t2-oroeja"]
      },
      component:()=>import("../views/home/child/students.vue")
    },
    {
      path:"editExam/:id",
      name:"editExam",
      meta:{
        authority_text:"编辑试题",
      },
      component:()=>import("../views/home/child/addExam.vue")
    },{
      path:"examClassify",
      beforeEnter:viewShow,
      meta:{
        open:true,
        authority_text:"试题分类",
         title:"试题管理",
         user_id:["axg8t2-oroeja"]
      },
      component:()=>import("../views/home/child/examClassify.vue")
    },
    //用户
    {
      path:"addUser",
      beforeEnter:viewShow,
      meta:{
        open:true,
        authority_text:"添加用户",
         title:"用户管理",
         user_id:["axg8t2-oroeja"]
      },
      component:()=>import("../views/home/child/addUser.vue")
    },
    {
      path:"showUser",
      beforeEnter:viewShow,
      meta:{
        open:true,
        authority_text:"用户展示",
         title:"用户管理",
         user_id:["kqpvys-hpzkdt","axg8t2-oroeja"]
      },
      component:()=>import("../views/home/child/showUser.vue")
    },{
      //考试
      path:"addText",
      beforeEnter:viewShow,
      meta:{
        open:true,
        authority_text:"添加考试",
         title:"考试管理",
         user_id:["kqpvys-hpzkdt","axg8t2-oroeja"]
      },
      component:()=>import("../views/home/child/addText.vue")
    },
    {
      path:"pageList",
      beforeEnter:viewShow,
      meta:{
        open:true,
        authority_text:"试卷列表",
        title:"考试管理",
        user_id:["kqpvys-hpzkdt","axg8t2-oroeja"]
      },
      component:()=>import("../views/home/child/pageList.vue")
    },
    {
      path:"addMenu",
      meta:{
        authority_text:"添加菜单",
      },
      component:()=>import("../views/home/child/addMenu.vue")
    },
    {
      path:"setPaper",
      meta:{
        authority_text:"创建试卷",
      },
      component:()=>import("../views/home/child/setPaper.vue")
    },
    {
      path:"readPaper",
      meta:{
        authority_text:"阅卷",
      },
      component:()=>import("../views/home/child/readPaper.vue")
    },
    {
      path:"readClass",
      meta:{
        authority_text:"批卷班级",
      },
      component:()=>import("../views/home/child/readClass.vue")
    },
    {
      path:"awaitPage",
      meta:{
        authority_text:"待批试卷",
      },
      component:()=>import("../views/home/child/awaitPage.vue")
    }
  ]
  let navdata = () =>{
    let getdata = window.sessionStorage.userInfo && JSON.parse(window.sessionStorage.userInfo).identity_text==="管理员" ?  [
     
        {
          name:"试题管理",
          child:[],
          user_id:"axg8t2-oroeja"
        },
        {
          name:"用户管理",
          child:[],
          user_id:"axg8t2-oroeja"
        },
        {
          name:"考试管理",
          child:[],
          user_id:"axg8t2-oroeja"
        },
        
        {
          name:"班级管理",
          child:[],
          user_id:"axg8t2-oroeja"
        }
  ]:[
    {
      name:"试题管理",
      child:[],
      user_id:"kqpvys-hpzkdt"
    },
    {
      name:"班级管理",
      child:[],
      user_id:"kqpvys-hpzkdt"
    }
   
  ]
  children.forEach(item=>{
    getdata.forEach((ite,index)=>{
      let user = window.sessionStorage.userInfo && JSON.parse(window.sessionStorage.userInfo).user_name;
        if(item.meta.title && (item.meta.title === ite.name)&&(item.meta.user_id && item.meta.user_id.find(ele=>ele === ite.user_id))){
            getdata[index].child.push({navName:item.meta.authority_text,navUrl:"/home/"+item.path})
        }
    })
})
return getdata
  }
    
    export {navdata}
 export default children;
